import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
/* import statement added */
import { ToastContainer } from "react-toastify";
/* import css statement added */
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ToastContainer /> {/* ToastContainer added inside the body tag */}
      </body>
    </html>
  );
}
